class Product {
  final String id;
  final String name;
  final String category;
  final int price;
  final String image;
  final double rating;
  final int reviews;
  final bool isAvailable;
  final String description;
  final List<String> specs;

  Product({
    required this.id,
    required this.name,
    required this.category,
    required this.price,
    required this.image,
    required this.rating,
    required this.reviews,
    required this.isAvailable,
    required this.description,
    required this.specs,
  });

  // Static list for single source of truth (until fully migrated to DB for products)
  static final List<Product> allProducts = [
    Product(
      id: '1',
      name: 'PS5 Digital Edition',
      category: 'PS 5',
      price: 50000,
      image: 'assets/images/ps5_digital.png',
      rating: 4.9,
      reviews: 128,
      isAvailable: true,
      description: 'PlayStation 5 Digital Edition tanpa disc drive',
      specs: ['825GB SSD', '4K Gaming', 'Ray Tracing'],
    ),
    Product(
      id: '2',
      name: 'PS5 Standard Edition',
      category: 'PS 5',
      price: 55000,
      image: 'assets/images/ps5_digital.png',
      rating: 4.8,
      reviews: 156,
      isAvailable: true,
      description: 'PlayStation 5 dengan Ultra HD Blu-ray disc drive',
      specs: ['825GB SSD', '4K Gaming', 'Disc Drive'],
    ),
    Product(
      id: '3',
      name: 'PlayStation 4 Pro',
      category: 'PS 4',
      price: 45000,
      image: 'assets/images/ps4_console.png',
      rating: 4.7,
      reviews: 95,
      isAvailable: true,
      description: 'PS4 Pro dengan performa gaming yang lebih tinggi',
      specs: ['1TB HDD', '4K Upscaling', 'HDR'],
    ),
    Product(
      id: '4',
      name: 'PS4 Slim 1TB',
      category: 'PS 4',
      price: 40000,
      image: 'assets/images/ps4_slim.png',
      rating: 4.6,
      reviews: 82,
      isAvailable: false,
      description: 'PS4 Slim dengan desain lebih ramping',
      specs: ['1TB HDD', 'Full HD Gaming', 'Compact Design'],
    ),
    Product(
      id: '5',
      name: 'PS4 Slim 500GB',
      category: 'PS 4',
      price: 35000,
      image: 'assets/images/ps4_slim.png',
      rating: 4.5,
      reviews: 67,
      isAvailable: true,
      description: 'PS4 Slim versi 500GB',
      specs: ['500GB HDD', 'Full HD Gaming', 'Budget Friendly'],
    ),
    Product(
      id: '6',
      name: 'PS3 Super Slim',
      category: 'PS 3',
      price: 25000,
      image: 'assets/images/ps3.png',
      rating: 4.3,
      reviews: 45,
      isAvailable: true,
      description: 'PS3 Super Slim dengan koleksi game klasik',
      specs: ['500GB HDD', 'Blu-ray Player', 'Classic Games'],
    ),
    Product(
      id: '7',
      name: 'PS3 Slim',
      category: 'PS 3',
      price: 25000,
      image: 'assets/images/ps3.png',
      rating: 4.2,
      reviews: 38,
      isAvailable: true,
      description: 'PS3 Slim untuk gaming retro',
      specs: ['320GB HDD', 'Blu-ray Player', 'WiFi'],
    ),
    Product(
      id: '8',
      name: 'PS2 Slim',
      category: 'PS 2',
      price: 20000,
      image: 'assets/images/ps2.png',
      rating: 4.5,
      reviews: 67,
      isAvailable: true,
      description: 'PS2 Slim - konsol legendaris',
      specs: ['DVD Player', 'Memory Card', 'Classic Gaming'],
    ),
    Product(
      id: '9',
      name: 'PS2 Fat',
      category: 'PS 2',
      price: 18000,
      image: 'assets/images/ps2.png',
      rating: 4.4,
      reviews: 52,
      isAvailable: false,
      description: 'PS2 Original dengan HDD support',
      specs: ['HDD Support', 'Network Adapter', 'Nostalgia'],
    ),
    Product(
      id: '10',
      name: 'God of War Ragnarok',
      category: 'KASET',
      price: 15000,
      image: 'assets/images/disc.png',
      rating: 4.9,
      reviews: 234,
      isAvailable: true,
      description: 'Game PS5 - God of War Ragnarok',
      specs: ['PS5 Exclusive', 'Action Adventure', '40+ Hours'],
    ),
    Product(
      id: '11',
      name: 'Spider-Man 2',
      category: 'KASET',
      price: 15000,
      image: 'assets/images/disc.png',
      rating: 4.8,
      reviews: 189,
      isAvailable: true,
      description: 'Game PS5 - Marvel Spider-Man 2',
      specs: ['PS5 Exclusive', 'Open World', 'Co-op Story'],
    ),
    Product(
      id: '12',
      name: 'FIFA 24',
      category: 'KASET',
      price: 12000,
      image: 'assets/images/disc.png',
      rating: 4.5,
      reviews: 156,
      isAvailable: true,
      description: 'Game sepak bola terbaru',
      specs: ['PS4/PS5', 'Sports', 'Online Multiplayer'],
    ),
    Product(
      id: '13',
      name: 'PS5 Slim Digital Edition',
      category: 'PS 5',
      price: 50000,
      image: 'assets/images/ps5_slim.png',
      rating: 4.9,
      reviews: 142,
      isAvailable: true,
      description:
          'PlayStation 5 Slim Digital Edition dengan desain lebih ramping',
      specs: ['1TB SSD', '4K Gaming', 'Ray Tracing'],
    ),
    Product(
      id: '14',
      name: 'PS5 Slim Disc Edition',
      category: 'PS 5',
      price: 55000,
      image: 'assets/images/ps5_slim.png',
      rating: 4.9,
      reviews: 118,
      isAvailable: true,
      description: 'PS5 Slim dengan Ultra HD Blu-ray disc drive',
      specs: ['1TB SSD', '4K Gaming', 'Disc Drive'],
    ),
    Product(
      id: '15',
      name: 'PS5 Pro',
      category: 'PS 5',
      price: 65000,
      image: 'assets/images/ps5_pro.png',
      rating: 5.0,
      reviews: 96,
      isAvailable: true,
      description: 'PlayStation 5 Pro dengan performa gaming kelas premium',
      specs: ['2TB SSD', '8K Support', 'Advanced Ray Tracing'],
    ),
    Product(
      id: '16',
      name: 'PS4 Pro 2TB',
      category: 'PS 4',
      price: 48000,
      image: 'assets/images/ps4_console.png',
      rating: 4.8,
      reviews: 73,
      isAvailable: true,
      description: 'PS4 Pro dengan kapasitas penyimpanan 2TB',
      specs: ['2TB HDD', '4K Upscaling', 'HDR'],
    ),
    Product(
      id: '17',
      name: 'PS4 Slim 1TB White',
      category: 'PS 4',
      price: 40000,
      image: 'assets/images/ps4_slim.png',
      rating: 4.6,
      reviews: 61,
      isAvailable: true,
      description: 'PS4 Slim 1TB dengan desain warna putih',
      specs: ['1TB HDD', 'Full HD Gaming', 'WiFi'],
    ),
    Product(
      id: '18',
      name: 'PS3 Super Slim 250GB',
      category: 'PS 3',
      price: 23000,
      image: 'assets/images/ps3.png',
      rating: 4.3,
      reviews: 41,
      isAvailable: true,
      description: 'PS3 Super Slim 250GB untuk koleksi game klasik',
      specs: ['250GB HDD', 'Blu-ray Player', 'WiFi'],
    ),
    Product(
      id: '19',
      name: 'PS2 Slim Black',
      category: 'PS 2',
      price: 20000,
      image: 'assets/images/ps2.png',
      rating: 4.5,
      reviews: 58,
      isAvailable: true,
      description: 'PS2 Slim warna hitam dengan berbagai koleksi game klasik',
      specs: ['DVD Player', 'Memory Card', 'Classic Gaming'],
    ),
    Product(
      id: '20',
      name: 'The Last of Us Part II',
      category: 'KASET',
      price: 15000,
      image: 'assets/images/disc.png',
      rating: 4.9,
      reviews: 176,
      isAvailable: true,
      description: 'Game action adventure dengan cerita yang mendalam',
      specs: ['PS4', 'Action Adventure', 'Single Player'],
    ),
    Product(
      id: '21',
      name: 'Gran Turismo 7',
      category: 'KASET',
      price: 15000,
      image: 'assets/images/disc.png',
      rating: 4.8,
      reviews: 134,
      isAvailable: true,
      description: 'Game balap mobil realistis untuk PlayStation',
      specs: ['PS4/PS5', 'Racing', 'Online Multiplayer'],
    ),
    Product(
      id: '22',
      name: 'Tekken 8',
      category: 'KASET',
      price: 15000,
      image: 'assets/images/disc.png',
      rating: 4.8,
      reviews: 121,
      isAvailable: true,
      description: 'Game fighting terbaru dengan berbagai karakter',
      specs: ['PS5', 'Fighting', 'Multiplayer'],
    ),
  ];
}
